add_library(hidapi STATIC)
target_include_directories(hidapi PUBLIC hidapi)
target_include_directories(hidapi PUBLIC hidapi/hidapi)

if(APPLE)
  target_sources(hidapi PRIVATE hidapi/mac/hid.c)
elseif(MSVC)
  target_sources(hidapi PRIVATE hidapi/windows/hid.c)
  target_link_libraries(hidapi PRIVATE setupapi)
else()
  find_package(Libudev)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND LIBUDEV_FOUND)
    target_sources(hidapi PRIVATE hidapi/linux/hid.c)
    target_link_libraries(hidapi PRIVATE udev)
  else()
    target_sources(hidapi PRIVATE hidapi/libusb/hid.c)
  endif()
endif()
